### ISSUE TITLE
silent option

### ISSUE THREAD

**Issue by orlin** [chmontgomery/gulp-help#28]
Have you tried to suppress the usual gulp log messages before and after the help output?  There is a `--silent` option discussed here gulpjs/gulp#492, but I don't see how to easily make use of it for certain tasks, such as `gulp help`.  By the time `gulpfile.js` is required the `process.argv` has been processed, or I'm missing something...

**Comment by chmontgomery** [comment]
Correct, `--silent` is passed to the gulp cli, so by the time a task is run, that option is set. There is no good way to hack the `.log()` function either because it's baked into the gulp cli, see: https://github.com/gulpjs/gulp/blob/master/bin/gulp.js#L48

The only thing I can think of is creating a wrapper around the gulp cli and using [proxyquire](https://github.com/thlorenz/proxyquire) to override the invocation to `require('gulp-util')` with your own thing that checks the gulp task name and disables the logging.

Either way, this doesn't seem like a thing I'd support via `gulp-help`. The best solution I got for you is `gulp help --silent` :(
